jobs:
  include:
    - stage: build0
      script: ./travis-ci.py 0
    - stage: build1
      script: ./travis-ci.py 1
    - stage: build2
      script: ./travis-ci.py 2
dist: bionic
language: cpp
addons:
  apt:
    packages:
    - libx11-xcb-dev
cache:
   directories:
    - $HOME/.cache/bazel/
